pattern=(
 "apple",
 "iphone",
 "DSMG",
 "SQLI",
 "DOCSIS",
 "SSID",
 "EKG",
 "MDD",
 "RUST",
 "PUBLIC KEY",
 "PAH",
 "FDDI",
 "VHD",
 "VPLS",
 "MCA",
 "XVU",
 "BP",
 "WBA",
 "PNG",
 "CTG",
 "NTP",
 "WWPN",
 "SAFE",
 "SOAR",
 "JTV",
 "LUN",
 "HDMI",
 "DVI",
 "VM",
 "NLP",
 "PPP",
 "OAUTH",
 "SAN",
 "DISPLAYPORT",
 "ACLS",
 "INR",
 "LAN",
 "ES6",
 "ORM",
 "B12",
 "AGILE",
 "USG",
 "IAAF",
 "RAID",
 "HIV",
 "BLE",
 "EPC",
 "PHC",
 "AKI",
 "OSI",
 "ISUP",
 "MSTP",
 "XTV",
 "INTSERV",
 "CSS",
 "JAR",
 "HTTP",
 "CDN",
 "API",
 "IDE",
 "ECG",
 "CSRF",
 "TLS",
 "MQTT",
 "BPM",
 "ZIGBEE",
 "SGSN",
 "EYIF",
 "CTAB",
 "RNK",
 "IP",
 "COVID 19",
 "DNF",
 "US",
 "CHD",
 "AH",
 "SIP",
 "PPE",
 "GFR",
 "POWERSHELL",
 "SFTP",
 "ANSIBLE",
 "PON",
 "LT",
 "CSR",
 "KVD",
 "NR",
 "NBA",
 "PUD",
 "CVA",
 "CBC",
 "RAAS",
 "IBD",
 "RFC",
 "SNMP",
 "PLT",
 "PZR",
 "HR",
 "TGA",
 "VRF",
 "HTML",
 "STD",
 "IAAS",
 "VPC",
 "DAC",
 "SIDS",
 "NSAID",
 "CLL",
 "SCT",
 "I2P",
 "DSLAM",
 "APC",
 "L2TP",
 "GIT",
 "GGSN",
 "ECC",
 "MRA",
 "TSUL",
 "COBIT",
 "NSCLC",
 "WIMAX",
 "MAV",
 "TUG",
 "ALP",
 "GUI",
 "TBI",
 "XOQ",
 "RKB",
 "SOAP",
 "KUB",
 "NOC",
 "HGB",
 "SODIMM",
 "MTEX",
 "STAT",
 "HSS",
 "ACS",
 "UT",
 "JAVA",
 "PFL",
 "LFT",
 "IPS",
 "IKE",
 "INAP",
 "PAGP",
 "SDK",
 "ONU",
 "DIMM",
 "EMM",
 "MHT",
 "MP3",
 "CRT",
 "IPAM",
 "ID",
 "BRAS",
 "ONK",
 "FIS",
 "ZTA",
 "RAM",
 "ATM",
 "MME",
 "ACL",
 "DEVSECOPS",
 "LP",
 "BSS",
 "HAAS",
 "DIFFIE HELLMAN",
 "VPN",
 "QID",
 "BLS",
 "SDH",
 "AIOPS",
 "ADSL",
 "WBC",
 "AHCI",
 "LDP",
 "MOQ",
 "TOGAF",
 "TENS",
 "MTP",
 "MS",
 "KDL",
 "IMS",
 "TIF",
 "JENKINS",
 "WAR",
 "PS 2",
 "TTYM",
 "FDD",
 "PEEP",
 "SATA",
 "KOTLIN",
 "SCLC",
 "DOCKER",
 "MOV",
 "UHS",
 "AST",
 "ZFS",
 "SAML",
 "TACE",
 "AES",
 "VXLAN",
 "CLI",
 "AR",
 "NFS",
 "ISCSI",
 "DNK",
 "ASIC",
 "FR",
 "TOR",
 "PMIS",
 "SASE",
 "HCO3",
 "TPDI",
 "SOB",
 "SECOPS",
 "FTB",
 "SMPP",
 "PBB",
 "IJF",
 "YAHB",
 "CVD",
 "VLAN",
 "STV",
 "NET",
 "NIV",
 "OT",
 "PKD",
 "AED",
 "PKG",
 "IBF",
 "PTCA",
 "VAD",
 "RIOTM",
 "BPD",
 "KHTB",
 "ATP",
 "DIC",
 "PED",
 "CPR",
 "DNAT",
 "GB",
 "RSVP",
 "KANBAN",
 "TKTI",
 "CRP",
 "SC",
 "FNA",
 "TSP",
 "NAT",
 "WAV",
 "EAK",
 "NVME",
 "TLI",
 "SSO",
 "RDP",
 "FPGA",
 "MAC",
 "ALG",
 "IFA",
 "SPF",
 "CNS",
 "IPD",
 "QOS",
 "TSH",
 "HIBS",
 "PAAS",
 "RAT",
 "CSMA CD",
 "ISP",
 "FHDYO",
 "ESR",
 "EMF",
 "MFA",
 "TERRAFORM",
 "HPT",
 "RTCP",
 "TIV",
 "LDH",
 "BXMK",
 "PATA",
 "VNC",
 "ICMP",
 "PYTHON",
 "CPU",
 "AJAX",
 "CI CD",
 "UDP",
 "2FA",
 "GLBP",
 "ERI",
 "TDYU",
 "THTY",
 "DHCP",
 "EBS",
 "CHF",
 "VOIP",
 "ESS",
 "LLDP",
 "GRAPHQL",
 "HCC",
 "CERT",
 "XR",
 "QQI",
 "USB C",
 "SNRI",
 "SSRI",
 "EIGRP",
 "NB IOT",
 "REST",
 "MVC",
 "DDOS",
 "RSRIM",
 "BMX",
 "SAS",
 "ORIF",
 "RSTP",
 "FIBA",
 "UWW",
 "AIDS",
 "DAAS",
 "SCRUM",
 "ECMO",
 "DNS",
 "YHQ",
 "EXE",
 "NAD",
 "SMTP",
 "SSV",
 "QUIC",
 "SIS",
 "DMZ",
 "PFT",
 "MVA",
 "ESP",
 "MRT",
 "RRMS",
 "UZASI",
 "MMS",
 "MI",
 "S3",
 "MDR",
 "RPM",
 "MGCP",
 "VATS",
 "FAAS",
 "GITLAB",
 "MAOI",
 "QTV",
 "INTERMEDIATE CA",
 "VTMM",
 "MD5",
 "ICF",
 "BIPAP",
 "IWF",
 "MVK",
 "EDS",
 "ITIL",
 "UFS",
 "HBV",
 "PCR",
 "FHH",
 "YAMD",
 "CTCA",
 "UEFA",
 "KUBERNETES",
 "MCTD",
 "C2",
 "MXIK",
 "PALS",
 "EMIS",
 "SRAM",
 "GPON",
 "PE",
 "PKCS",
 "WAF",
 "BSMP",
 "TFA",
 "TTL",
 "ALS",
 "NETOPS",
 "BYD",
 "GAS",
 "TLD",
 "PFS",
 "PKI",
 "HPV",
 "FAP",
 "PAM",
 "GRPC",
 "IIBB",
 "YPAK",
 "STIV",
 "RBAC",
 "INPS",
 "ST",
 "TID",
 "LM",
 "USB A",
 "BID",
 "ACE",
 "UZA",
 "PCD",
 "EMG",
 "HHS",
 "SSL",
 "NGFW",
 "FCOE",
 "FILA",
 "SDSL",
 "FVC",
 "PERL",
 "ER",
 "HIVRNA",
 "CMD",
 "DVT",
 "SMPB",
 "BIOS",
 "PBB TE",
 "ABG",
 "U2F",
 "AMQP",
 "IOT",
 "ARB",
 "IBS",
 "CF",
 "LAD",
 "FIG",
 "GIF",
 "PID",
 "OTC",
 "SVN",
 "TTK",
 "PS1",
 "ACTH",
 "EPON",
 "CD",
 "EPROM",
 "CPAP",
 "PXE",
 "PO",
 "DNMT",
 "GITHUB",
 "MTRM",
 "PHP",
 "FVV",
 "CKD",
 "SAAS",
 "EDMS",
 "DER",
 "TCP IP",
 "YAHT",
 "UYJ",
 "DES",
 "YHM",
 "RTP",
 "CABG",
 "SIEM",
 "GPS",
 "ITF",
 "DOS",
 "DOH",
 "KTM",
 "PVD",
 "FBS",
 "CPT",
 "PPTP",
 "JS",
 "ERP",
 "LTE",
 "CD4",
 "IPV4",
 "DKA",
 "NFC",
 "UC",
 "PPT",
 "FTP",
 "VRE",
 "CMT",
 "APK",
 "SIGFOX",
 "FIREWIRE",
 "CFS",
 "TDP",
 "MITM",
 "BCR ABL",
 "MAP",
 "RBC",
 "DMT",
 "CIDR",
 "BICC",
 "EEPROM",
 "DBQ",
 "LEAN",
 "CIFS",
 "GO",
 "PRBC",
 "SGW",
 "FHRP",
 "DVD",
 "HTN",
 "FINA",
 "CA",
 "CT",
 "EGD",
 "HDD",
 "PPD",
 "SNAT",
 "IVIG",
 "MEG",
 "VHDX",
 "APT",
 "XDR",
 "RUBY",
 "DBMS",
 "DL",
 "OIDC",
 "PSTN",
 "ICD",
 "BITBUCKET",
 "T3",
 "PNA",
 "VMDK",
 "HEMIS",
 "QTMT",
 "ITU",
 "UPS",
 "MPO",
 "SOC",
 "MDM",
 "COAP",
 "MMR",
 "TYOB",
 "RARP",
 "IIOT",
 "ELB",
 "NDP",
 "TTA",
 "PTH",
 "BGP",
 "HEPA",
 "RNS",
 "DQMB",
 "EAR",
 "DNR",
 "IGMP",
 "MRB",
 "TMA",
 "LDAP",
 "CWDM",
 "MERS",
 "EUS",
 "TGF",
 "QMMB",
 "XMK",
 "CERTIFICATE",
 "TTV",
 "LDL",
 "DSE",
 "RDS",
 "ML",
 "IMAP",
 "FW",
 "TYPESCRIPT",
 "MIM",
 "FTPS",
 "RFT",
 "JSST",
 "DSM",
 "BMR",
 "LORA",
 "RJ45",
 "OVF",
 "WEBID",
 "PT",
 "GERD",
 "PRP",
 "BUN",
 "DSZV",
 "NCP",
 "SDP",
 "SPMS",
 "SQL",
 "OLT",
 "SARS",
 "PO2",
 "SONET",
 "DLP",
 "CRM",
 "SWIFT",
 "FUP",
 "SSH",
 "DWDM",
 "WLAN",
 "DGK",
 "RIP",
 "PTA",
 "ROOT CA",
 "USB",
 "DPT",
 "CDMA",
 "XML",
 "MDS",
 "DNSSEC",
 "STAAS",
 "PET",
 "AML",
 "OSPF",
 "ARP",
 "SES",
 "PTSD",
 "BMD",
 "AS",
 "CAAS",
 "DAN",
 "PDF",
 "HISS",
 "DOC",
 "BUP",
 "DRAAS",
 "NFV",
 "XP",
 "DIFFSERV",
 "HMAC",
 "PGP",
 "UFC",
 "SNAP",
 "PMS",
 "EDR",
 "WI FI",
 "TTS",
 "ADHD",
 "ICU",
 "NVRAM",
 "RPOC",
 "CXR",
 "JBOD",
 "GPU",
 "BMP",
 "SCC",
 "VDI",
 "PRIVATE KEY",
 "FBC",
 "DM",
 "FIDE",
 "HSRP",
 "KB",
 "XSS",
 "UEM",
 "MPV",
 "YUM",
 "HUS",
 "YAIM",
 "IETF",
 "HCT",
 "3DES",
 "PPMS",
 "STP",
 "HBA",
 "GSM",
 "MTRK",
 "OA",
 "CRUD",
 "AVI",
 "CAD",
 "PKEI",
 "CD8",
 "XLS",
 "MRI",
 "IHF",
 "GPG",
 "YAML",
 "KMK",
 "PGW",
 "TTJ",
 "MMTV",
 "HIFZ",
 "G6PD",
 "ISO",
 "JSP",
 "BOOTP",
 "SMB",
 "UZI",
 "CARP",
 "BMK",
 "WBO",
 "VQ",
 "MRK",
 "RPR",
 "BASH",
 "BCG",
 "IVF",
 "NGT",
 "BMI",
 "LCD",
 "SD WAN",
 "ARDS",
 "IDS",
 "EEG",
 "CTA",
 "BTV",
 "STIR",
 "BMT",
 "VDSL",
 "COPD",
 "OTP",
 "HCV",
 "CDP",
 "DSL",
 "LACP",
 "BAAS",
 "ENT",
 "OOP",
 "WWN",
 "KMP",
 "BAT",
 "TCP",
 "CSMA CA",
 "HTTPS",
 "SSB",
 "OIV",
 "ICS",
 "GMK",
 "HTTP2",
 "XSLT",
 "NAMTV",
 "TTY",
 "RSHTIOM",
 "TTB",
 "AFP",
 "OCD",
 "FIDO",
 "VTP",
 "CREA",
 "HDL",
 "DSQ",
 "NIC",
 "EC2",
 "VGA",
 "AGC",
 "TTM",
 "DOTS",
 "GAD",
 "CASB",
 "BYOD",
 "ATV",
 "T4",
 "IUD",
 "WTA",
 "MPLS",
 "PAT",
 "UEBA",
 "HCG",
 "TMI",
 "LCP",
 "TLC",
 "ALT",
 "JWT",
 "RPA",
 "CSF",
 "AIBA",
 "MP4",
 "ERCP",
 "URTI",
 "RSV",
 "ISU",
 "HLA",
 "HIRS",
 "BPH",
 "IPSEC",
 "IAM",
 "TPU",
 "P2P",
 "PRN",
 "EVPN",
 "MCS",
 "VRRP",
 "MMB",
 "AI",
 "CSV",
 "PCOS",
 "NAS",
 "OSS",
 "SSD",
 "TIA",
 "COPE",
 "SSKS",
 "FEV1",
 "IM",
 "KT",
 "URL",
 "UTI",
 "RSA",
 "LC",
 "PSA",
 "SLE",
 "5G",
 "IPF",
 "DRAM",
 "XIF",
 "UTM",
 "EIG",
 "TFTP",
 "LAMBDA",
 "IV",
 "CML",
 "FISH",
 "LRTI",
 "PBXR",
 "WDM",
 "ISDN",
 "FTV",
 "NTU",
 "JSON",
 "X RAY",
 "A1C",
 "BLOWFISH",
 "EIIB",
 "DKTM",
 "TMPM",
 "GRE",
 "RFID",
 "OAK",
 "PIIMA",
 "SDN",
 "STT",
 "SCP",
 "KEY EXCHANGE",
 "HRT",
 "RA",
 "WAN",
 "DVQK",
 "TCA",
 "SVK",
 "APGAR",
 "VMX",
 "UASH",
 "DBAAS",
 "VR",
 "ASP",
 "PEM",
 "IPV6",
 "LLM",
 "DEVOPS",
 "GCS"
)
_replacement = {
 "DSMG": "dee es em jii ",
 "SQLI": "es qyuu ell ayy ",
 "DOCSIS": "dee o'vv sii es ayy es ",
 "SSID": "es es ayy dee ",
 "EKG": "iii kiyy jii ",
 "MDD": "em dee dee ",
 "RUST": "arr yuu es tii ",
 "PUBLIC KEY": "ppii yuu bii ell ayy sii kiyy iii vay ",
 "PAH": "ppii eeyy eych ",
 "FDDI": "eff dee dee ayy ",
 "VHD": "vii eych dee ",
 "VPLS": "vii ppii ell es ",
 "MCA": "em sii eeyy ",
 "XVU": "eks vii yuu ",
 "BP": "bii ppii ",
 "WBA": "dabilyu bii eeyy ",
 "PNG": "ppii enn jii ",
 "CTG": "sii tii jii ",
 "NTP": "enn tii ppii ",
 "WWPN": "dabilyu dabilyu ppii enn ",
 "SAFE": "es eeyy eff iii ",
 "SOAR": "es o'vv eeyy arr ",
 "JTV": "jeyy tii vii ",
 "LUN": "ell yuu enn ",
 "HDMI": "eych dee em ayy ",
 "DVI": "dee vii ayy ",
 "VM": "vii em ",
 "NLP": "enn ell ppii ",
 "PPP": "ppii ppii ppii ",
 "OAUTH": "o'vv eeyy yuu tii eych ",
 "SAN": "es eeyy enn ",
 "DISPLAYPORT": "dee ayy es ppii ell eeyy vay ppii o'vv arr tii ",
 "ACLS": "eeyy sii ell es ",
 "INR": "ayy enn arr ",
 "LAN": "ell eeyy enn ",
 "ES6": "iii es olti ",
 "ORM": "o'vv arr em ",
 "B12": "bii bir ikki ",
 "AGILE": "eeyy jii ayy ell iii ",
 "USG": "yuu es jii ",
 "IAAF": "ayy eeyy eeyy eff ",
 "RAID": "arr eeyy ayy dee ",
 "HIV": "eych ayy vii ",
 "BLE": "bii ell iii ",
 "EPC": "iii ppii sii ",
 "PHC": "ppii eych sii ",
 "AKI": "eeyy kiyy ayy ",
 "OSI": "o'vv es ayy ",
 "ISUP": "ayy es yuu ppii ",
 "MSTP": "em es tii ppii ",
 "XTV": "eks tii vii ",
 "INTSERV": "ayy enn tii es iii arr vii ",
 "CSS": "sii es es ",
 "JAR": "jeyy eeyy arr ",
 "HTTP": "eych tii tii ppii ",
 "CDN": "sii dee enn ",
 "API": "eeyy ppii ayy ",
 "IDE": "ayy dee iii ",
 "ECG": "iii sii jii ",
 "CSRF": "sii es arr eff ",
 "TLS": "tii ell es ",
 "MQTT": "em qyuu tii tii ",
 "BPM": "bii ppii em ",
 "ZIGBEE": "zed ayy jii bii iii iii ",
 "SGSN": "es jii es enn ",
 "EYIF": "iii vay ayy eff ",
 "CTAB": "sii tii eeyy bii ",
 "RNK": "arr enn kiyy ",
 "IP": "ayy ppii ",
 "COVID-19": "sii o'vv vii ayy dee   bir to'qqiz ",
 "DNF": "dee enn eff ",
 "US": "yuu es ",
 "CHD": "sii eych dee ",
 "AH": "eeyy eych ",
 "SIP": "es ayy ppii ",
 "PPE": "ppii ppii iii ",
 "GFR": "jii eff arr ",
 "POWERSHELL": "ppii o'vv dabilyu iii arr es eych iii ell ell ",
 "SFTP": "es eff tii ppii ",
 "ANSIBLE": "eeyy enn es ayy bii ell iii ",
 "PON": "ppii o'vv enn ",
 "LT": "ell tii ",
 "CSR": "sii es arr ",
 "KVD": "kiyy vii dee ",
 "NR": "enn arr ",
 "NBA": "enn bii eeyy ",
 "PUD": "ppii yuu dee ",
 "CVA": "sii vii eeyy ",
 "CBC": "sii bii sii ",
 "RAAS": "arr eeyy eeyy es ",
 "IBD": "ayy bii dee ",
 "RFC": "arr eff sii ",
 "SNMP": "es enn em ppii ",
 "PLT": "ppii ell tii ",
 "PZR": "ppii zed arr ",
 "HR": "eych arr ",
 "TGA": "tii jii eeyy ",
 "VRF": "vii arr eff ",
 "HTML": "eych tii em ell ",
 "STD": "es tii dee ",
 "IAAS": "ayy eeyy eeyy es ",
 "VPC": "vii ppii sii ",
 "DAC": "dee eeyy sii ",
 "SIDS": "es ayy dee es ",
 "NSAID": "enn es eeyy ayy dee ",
 "CLL": "sii ell ell ",
 "SCT": "es sii tii ",
 "I2P": "ayy ikki ppii ",
 "DSLAM": "dee es ell eeyy em ",
 "APC": "eeyy ppii sii ",
 "L2TP": "ell ikki tii ppii ",
 "GIT": "jii ayy tii ",
 "GGSN": "jii jii es enn ",
 "ECC": "iii sii sii ",
 "MRA": "em arr eeyy ",
 "TSUL": "tii es yuu ell ",
 "COBIT": "sii o'vv bii ayy tii ",
 "NSCLC": "enn es sii ell sii ",
 "WIMAX": "dabilyu ayy em eeyy eks ",
 "MAV": "em eeyy vii ",
 "TUG": "tii yuu jii ",
 "ALP": "eeyy ell ppii ",
 "GUI": "jii yuu ayy ",
 "TBI": "tii bii ayy ",
 "XOQ": "eks o'vv qyuu ",
 "RKB": "arr kiyy bii ",
 "SOAP": "es o'vv eeyy ppii ",
 "KUB": "kiyy yuu bii ",
 "NOC": "enn o'vv sii ",
 "HGB": "eych jii bii ",
 "SODIMM": "es o'vv dee ayy em em ",
 "MTEX": "em tii iii eks ",
 "STAT": "es tii eeyy tii ",
 "HSS": "eych es es ",
 "ACS": "eeyy sii es ",
 "UT": "yuu tii ",
 "JAVA": "jeyy eeyy vii eeyy ",
 "PFL": "ppii eff ell ",
 "LFT": "ell eff tii ",
 "IPS": "ayy ppii es ",
 "IKE": "ayy kiyy iii ",
 "INAP": "ayy enn eeyy ppii ",
 "PAGP": "ppii eeyy jii ppii ",
 "SDK": "es dee kiyy ",
 "ONU": "o'vv enn yuu ",
 "DIMM": "dee ayy em em ",
 "EMM": "iii em em ",
 "MHT": "em eych tii ",
 "MP3": "em ppii uch ",
 "CRT": "sii arr tii ",
 "IPAM": "ayy ppii eeyy em ",
 "ID": "ayy dee ",
 "BRAS": "bii arr eeyy es ",
 "ONK": "o'vv enn kiyy ",
 "FIS": "eff ayy es ",
 "ZTA": "zed tii eeyy ",
 "RAM": "arr eeyy em ",
 "ATM": "eeyy tii em ",
 "MME": "em em iii ",
 "ACL": "eeyy sii ell ",
 "DEVSECOPS": "dee iii vii es iii sii o'vv ppii es ",
 "LP": "ell ppii ",
 "BSS": "bii es es ",
 "HAAS": "eych eeyy eeyy es ",
 "DIFFIE-HELLMAN": "dee ayy eff eff ayy iii   eych iii ell ell em eeyy enn ",
 "VPN": "vii ppii enn ",
 "QID": "qyuu ayy dee ",
 "BLS": "bii ell es ",
 "SDH": "es dee eych ",
 "AIOPS": "eeyy ayy o'vv ppii es ",
 "ADSL": "eeyy dee es ell ",
 "WBC": "dabilyu bii sii ",
 "AHCI": "eeyy eych sii ayy ",
 "LDP": "ell dee ppii ",
 "MOQ": "em o'vv qyuu ",
 "TOGAF": "tii o'vv jii eeyy eff ",
 "TENS": "tii iii enn es ",
 "MTP": "em tii ppii ",
 "MS": "em es ",
 "KDL": "kiyy dee ell ",
 "IMS": "ayy em es ",
 "TIF": "tii ayy eff ",
 "JENKINS": "jeyy iii enn kiyy ayy enn es ",
 "WAR": "dabilyu eeyy arr ",
 "PS/2": "ppii es   ikki ",
 "TTYM": "tii tii vay em ",
 "FDD": "eff dee dee ",
 "PEEP": "ppii iii iii ppii ",
 "SATA": "es eeyy tii eeyy ",
 "KOTLIN": "kiyy o'vv tii ell ayy enn ",
 "SCLC": "es sii ell sii ",
 "DOCKER": "dee o'vv sii kiyy iii arr ",
 "MOV": "em o'vv vii ",
 "UHS": "yuu eych es ",
 "AST": "eeyy es tii ",
 "ZFS": "zed eff es ",
 "SAML": "es eeyy em ell ",
 "TACE": "tii eeyy sii iii ",
 "AES": "eeyy iii es ",
 "VXLAN": "vii eks ell eeyy enn ",
 "CLI": "sii ell ayy ",
 "AR": "eeyy arr ",
 "NFS": "enn eff es ",
 "ISCSI": "ayy es sii es ayy ",
 "DNK": "dee enn kiyy ",
 "ASIC": "eeyy es ayy sii ",
 "FR": "eff arr ",
 "TOR": "tii o'vv arr ",
 "PMIS": "ppii em ayy es ",
 "SASE": "es eeyy es iii ",
 "HCO3": "eych sii o'vv uch ",
 "TPDI": "tii ppii dee ayy ",
 "SOB": "es o'vv bii ",
 "SECOPS": "es iii sii o'vv ppii es ",
 "FTB": "eff tii bii ",
 "SMPP": "es em ppii ppii ",
 "PBB": "ppii bii bii ",
 "IJF": "ayy jeyy eff ",
 "YAHB": "vay eeyy eych bii ",
 "CVD": "sii vii dee ",
 "VLAN": "vii ell eeyy enn ",
 "STV": "es tii vii ",
 "NET": "enn iii tii ",
 "NIV": "enn ayy vii ",
 "OT": "o'vv tii ",
 "PKD": "ppii kiyy dee ",
 "AED": "eeyy iii dee ",
 "PKG": "ppii kiyy jii ",
 "IBF": "ayy bii eff ",
 "PTCA": "ppii tii sii eeyy ",
 "VAD": "vii eeyy dee ",
 "RIOTM": "arr ayy o'vv tii em ",
 "BPD": "bii ppii dee ",
 "KHTB": "kiyy eych tii bii ",
 "ATP": "eeyy tii ppii ",
 "DIC": "dee ayy sii ",
 "PED": "ppii iii dee ",
 "CPR": "sii ppii arr ",
 "DNAT": "dee enn eeyy tii ",
 "GB": "jii bii ",
 "RSVP": "arr es vii ppii ",
 "KANBAN": "kiyy eeyy enn bii eeyy enn ",
 "TKTI": "tii kiyy tii ayy ",
 "CRP": "sii arr ppii ",
 "SC": "es sii ",
 "FNA": "eff enn eeyy ",
 "TSP": "tii es ppii ",
 "NAT": "enn eeyy tii ",
 "WAV": "dabilyu eeyy vii ",
 "EAK": "iii eeyy kiyy ",
 "NVME": "enn vii em iii ",
 "TLI": "tii ell ayy ",
 "SSO": "es es o'vv ",
 "RDP": "arr dee ppii ",
 "FPGA": "eff ppii jii eeyy ",
 "MAC": "em eeyy sii ",
 "ALG": "eeyy ell jii ",
 "IFA": "ayy eff eeyy ",
 "SPF": "es ppii eff ",
 "CNS": "sii enn es ",
 "IPD": "ayy ppii dee ",
 "QOS": "qyuu o'vv es ",
 "TSH": "tii es eych ",
 "HIBS": "eych ayy bii es ",
 "PAAS": "ppii eeyy eeyy es ",
 "RAT": "arr eeyy tii ",
 "CSMA/CD": "sii es em eeyy   sii dee ",
 "ISP": "ayy es ppii ",
 "FHDYO": "eff eych dee vay o'vv ",
 "ESR": "iii es arr ",
 "EMF": "iii em eff ",
 "MFA": "em eff eeyy ",
 "TERRAFORM": "tii iii arr arr eeyy eff o'vv arr em ",
 "HPT": "eych ppii tii ",
 "RTCP": "arr tii sii ppii ",
 "TIV": "tii ayy vii ",
 "LDH": "ell dee eych ",
 "BXMK": "bii eks em kiyy ",
 "PATA": "ppii eeyy tii eeyy ",
 "VNC": "vii enn sii ",
 "ICMP": "ayy sii em ppii ",
 "PYTHON": "ppii vay tii eych o'vv enn ",
 "CPU": "sii ppii yuu ",
 "AJAX": "eeyy jeyy eeyy eks ",
 "CI/CD": "sii ayy   sii dee ",
 "UDP": "yuu dee ppii ",
 "2FA": "ikki eff eeyy ",
 "GLBP": "jii ell bii ppii ",
 "ERI": "iii arr ayy ",
 "TDYU": "tii dee vay yuu ",
 "THTY": "tii eych tii vay ",
 "DHCP": "dee eych sii ppii ",
 "EBS": "iii bii es ",
 "CHF": "sii eych eff ",
 "VOIP": "vii o'vv ayy ppii ",
 "ESS": "iii es es ",
 "LLDP": "ell ell dee ppii ",
 "GRAPHQL": "jii arr eeyy ppii eych qyuu ell ",
 "HCC": "eych sii sii ",
 "CERT": "sii iii arr tii ",
 "XR": "eks arr ",
 "QQI": "qyuu qyuu ayy ",
 "USB-C": "yuu es bii   sii ",
 "SNRI": "es enn arr ayy ",
 "SSRI": "es es arr ayy ",
 "EIGRP": "iii ayy jii arr ppii ",
 "NB-IOT": "enn bii   ayy o'vv tii ",
 "REST": "arr iii es tii ",
 "MVC": "em vii sii ",
 "DDOS": "dee dee o'vv es ",
 "RSRIM": "arr es arr ayy em ",
 "BMX": "bii em eks ",
 "SAS": "es eeyy es ",
 "ORIF": "o'vv arr ayy eff ",
 "RSTP": "arr es tii ppii ",
 "FIBA": "eff ayy bii eeyy ",
 "UWW": "yuu dabilyu dabilyu ",
 "AIDS": "eeyy ayy dee es ",
 "DAAS": "dee eeyy eeyy es ",
 "SCRUM": "es sii arr yuu em ",
 "ECMO": "iii sii em o'vv ",
 "DNS": "dee enn es ",
 "YHQ": "vay eych qyuu ",
 "EXE": "iii eks iii ",
 "NAD": "enn eeyy dee ",
 "SMTP": "es em tii ppii ",
 "SSV": "es es vii ",
 "QUIC": "qyuu yuu ayy sii ",
 "SIS": "es ayy es ",
 "DMZ": "dee em zed ",
 "PFT": "ppii eff tii ",
 "MVA": "em vii eeyy ",
 "ESP": "iii es ppii ",
 "MRT": "em arr tii ",
 "RRMS": "arr arr em es ",
 "UZASI": "yuu zed eeyy es ayy ",
 "MMS": "em em es ",
 "MI": "em ayy ",
 "S3": "es uch ",
 "MDR": "em dee arr ",
 "RPM": "arr ppii em ",
 "MGCP": "em jii sii ppii ",
 "VATS": "vii eeyy tii es ",
 "FAAS": "eff eeyy eeyy es ",
 "GITLAB": "jii ayy tii ell eeyy bii ",
 "MAOI": "em eeyy o'vv ayy ",
 "QTV": "qyuu tii vii ",
 "INTERMEDIATE CA": "ayy enn tii iii arr em iii dee ayy eeyy tii iii sii eeyy ",
 "VTMM": "vii tii em em ",
 "MD5": "em dee besh ",
 "ICF": "ayy sii eff ",
 "BIPAP": "bii ayy ppii eeyy ppii ",
 "IWF": "ayy dabilyu eff ",
 "MVK": "em vii kiyy ",
 "EDS": "iii dee es ",
 "ITIL": "ayy tii ayy ell ",
 "UFS": "yuu eff es ",
 "HBV": "eych bii vii ",
 "PCR": "ppii sii arr ",
 "FHH": "eff eych eych ",
 "YAMD": "vay eeyy em dee ",
 "CTCA": "sii tii sii eeyy ",
 "UEFA": "yuu iii eff eeyy ",
 "KUBERNETES": "kiyy yuu bii iii arr enn iii tii iii es ",
 "MCTD": "em sii tii dee ",
 "C2": "sii ikki ",
 "MXIK": "em eks ayy kiyy ",
 "PALS": "ppii eeyy ell es ",
 "EMIS": "iii em ayy es ",
 "SRAM": "es arr eeyy em ",
 "GPON": "jii ppii o'vv enn ",
 "PE": "ppii iii ",
 "PKCS": "ppii kiyy sii es ",
 "WAF": "dabilyu eeyy eff ",
 "BSMP": "bii es em ppii ",
 "TFA": "tii eff eeyy ",
 "TTL": "tii tii ell ",
 "ALS": "eeyy ell es ",
 "NETOPS": "enn iii tii o'vv ppii es ",
 "BYD": "bii vay dee ",
 "GAS": "jii eeyy es ",
 "TLD": "tii ell dee ",
 "PFS": "ppii eff es ",
 "PKI": "ppii kiyy ayy ",
 "HPV": "eych ppii vii ",
 "FAP": "eff eeyy ppii ",
 "PAM": "ppii eeyy em ",
 "GRPC": "jii arr ppii sii ",
 "IIBB": "ayy ayy bii bii ",
 "YPAK": "vay ppii eeyy kiyy ",
 "STIV": "es tii ayy vii ",
 "RBAC": "arr bii eeyy sii ",
 "INPS": "ayy enn ppii es ",
 "ST": "es tii ",
 "TID": "tii ayy dee ",
 "LM": "ell em ",
 "USB-A": "yuu es bii   eeyy ",
 "BID": "bii ayy dee ",
 "ACE": "eeyy sii iii ",
 "UZA": "yuu zed eeyy ",
 "PCD": "ppii sii dee ",
 "EMG": "iii em jii ",
 "HHS": "eych eych es ",
 "SSL": "es es ell ",
 "NGFW": "enn jii eff dabilyu ",
 "FCOE": "eff sii o'vv iii ",
 "FILA": "eff ayy ell eeyy ",
 "SDSL": "es dee es ell ",
 "FVC": "eff vii sii ",
 "PERL": "ppii iii arr ell ",
 "ER": "iii arr ",
 "HIVRNA": "eych ayy vii arr enn eeyy ",
 "CMD": "sii em dee ",
 "DVT": "dee vii tii ",
 "SMPB": "es em ppii bii ",
 "BIOS": "bii ayy o'vv es ",
 "PBB-TE": "ppii bii bii   tii iii ",
 "ABG": "eeyy bii jii ",
 "U2F": "yuu ikki eff ",
 "AMQP": "eeyy em qyuu ppii ",
 "IOT": "ayy o'vv tii ",
 "ARB": "eeyy arr bii ",
 "IBS": "ayy bii es ",
 "CF": "sii eff ",
 "LAD": "ell eeyy dee ",
 "FIG": "eff ayy jii ",
 "GIF": "jii ayy eff ",
 "PID": "ppii ayy dee ",
 "OTC": "o'vv tii sii ",
 "SVN": "es vii enn ",
 "TTK": "tii tii kiyy ",
 "PS1": "ppii es bir ",
 "ACTH": "eeyy sii tii eych ",
 "EPON": "iii ppii o'vv enn ",
 "CD": "sii dee ",
 "EPROM": "iii ppii arr o'vv em ",
 "CPAP": "sii ppii eeyy ppii ",
 "PXE": "ppii eks iii ",
 "PO": "ppii o'vv ",
 "DNMT": "dee enn em tii ",
 "GITHUB": "jii ayy tii eych yuu bii ",
 "MTRM": "em tii arr em ",
 "PHP": "ppii eych ppii ",
 "FVV": "eff vii vii ",
 "CKD": "sii kiyy dee ",
 "SAAS": "es eeyy eeyy es ",
 "EDMS": "iii dee em es ",
 "DER": "dee iii arr ",
 "TCP/IP": "tii sii ppii   ayy ppii ",
 "YAHT": "vay eeyy eych tii ",
 "UYJ": "yuu vay jeyy ",
 "DES": "dee iii es ",
 "YHM": "vay eych em ",
 "RTP": "arr tii ppii ",
 "CABG": "sii eeyy bii jii ",
 "SIEM": "es ayy iii em ",
 "GPS": "jii ppii es ",
 "ITF": "ayy tii eff ",
 "DOS": "dee o'vv es ",
 "DOH": "dee o'vv eych ",
 "KTM": "kiyy tii em ",
 "PVD": "ppii vii dee ",
 "FBS": "eff bii es ",
 "CPT": "sii ppii tii ",
 "PPTP": "ppii ppii tii ppii ",
 "JS": "jeyy es ",
 "ERP": "iii arr ppii ",
 "LTE": "ell tii iii ",
 "CD4": "sii dee to'rt ",
 "IPV4": "ayy ppii vii to'rt ",
 "DKA": "dee kiyy eeyy ",
 "NFC": "enn eff sii ",
 "UC": "yuu sii ",
 "PPT": "ppii ppii tii ",
 "FTP": "eff tii ppii ",
 "VRE": "vii arr iii ",
 "CMT": "sii em tii ",
 "APK": "eeyy ppii kiyy ",
 "SIGFOX": "es ayy jii eff o'vv eks ",
 "FIREWIRE": "eff ayy arr iii dabilyu ayy arr iii ",
 "CFS": "sii eff es ",
 "TDP": "tii dee ppii ",
 "MITM": "em ayy tii em ",
 "BCR-ABL": "bii sii arr   eeyy bii ell ",
 "MAP": "em eeyy ppii ",
 "RBC": "arr bii sii ",
 "DMT": "dee em tii ",
 "CIDR": "sii ayy dee arr ",
 "BICC": "bii ayy sii sii ",
 "EEPROM": "iii iii ppii arr o'vv em ",
 "DBQ": "dee bii qyuu ",
 "LEAN": "ell iii eeyy enn ",
 "CIFS": "sii ayy eff es ",
 "GO": "jii o'vv ",
 "PRBC": "ppii arr bii sii ",
 "SGW": "es jii dabilyu ",
 "FHRP": "eff eych arr ppii ",
 "DVD": "dee vii dee ",
 "HTN": "eych tii enn ",
 "FINA": "eff ayy enn eeyy ",
 "CA": "sii eeyy ",
 "CT": "sii tii ",
 "EGD": "iii jii dee ",
 "HDD": "eych dee dee ",
 "PPD": "ppii ppii dee ",
 "SNAT": "es enn eeyy tii ",
 "IVIG": "ayy vii ayy jii ",
 "MEG": "em iii jii ",
 "VHDX": "vii eych dee eks ",
 "APT": "eeyy ppii tii ",
 "XDR": "eks dee arr ",
 "RUBY": "arr yuu bii vay ",
 "DBMS": "dee bii em es ",
 "DL": "dee ell ",
 "OIDC": "o'vv ayy dee sii ",
 "PSTN": "ppii es tii enn ",
 "ICD": "ayy sii dee ",
 "BITBUCKET": "bii ayy tii bii yuu sii kiyy iii tii ",
 "T3": "tii uch ",
 "PNA": "ppii enn eeyy ",
 "VMDK": "vii em dee kiyy ",
 "HEMIS": "eych iii em ayy es ",
 "QTMT": "qyuu tii em tii ",
 "ITU": "ayy tii yuu ",
 "UPS": "yuu ppii es ",
 "MPO": "em ppii o'vv ",
 "SOC": "es o'vv sii ",
 "MDM": "em dee em ",
 "COAP": "sii o'vv eeyy ppii ",
 "MMR": "em em arr ",
 "TYOB": "tii vay o'vv bii ",
 "RARP": "arr eeyy arr ppii ",
 "IIOT": "ayy ayy o'vv tii ",
 "ELB": "iii ell bii ",
 "NDP": "enn dee ppii ",
 "TTA": "tii tii eeyy ",
 "PTH": "ppii tii eych ",
 "BGP": "bii jii ppii ",
 "HEPA": "eych iii ppii eeyy ",
 "RNS": "arr enn es ",
 "DQMB": "dee qyuu em bii ",
 "EAR": "iii eeyy arr ",
 "DNR": "dee enn arr ",
 "IGMP": "ayy jii em ppii ",
 "MRB": "em arr bii ",
 "TMA": "tii em eeyy ",
 "LDAP": "ell dee eeyy ppii ",
 "CWDM": "sii dabilyu dee em ",
 "MERS": "em iii arr es ",
 "EUS": "iii yuu es ",
 "TGF": "tii jii eff ",
 "QMMB": "qyuu em em bii ",
 "XMK": "eks em kiyy ",
 "CERTIFICATE": "sii iii arr tii ayy eff ayy sii eeyy tii iii ",
 "TTV": "tii tii vii ",
 "LDL": "ell dee ell ",
 "DSE": "dee es iii ",
 "RDS": "arr dee es ",
 "ML": "em ell ",
 "IMAP": "ayy em eeyy ppii ",
 "FW": "eff dabilyu ",
 "TYPESCRIPT": "tii vay ppii iii es sii arr ayy ppii tii ",
 "MIM": "em ayy em ",
 "FTPS": "eff tii ppii es ",
 "RFT": "arr eff tii ",
 "JSST": "jeyy es es tii ",
 "DSM": "dee es em ",
 "BMR": "bii em arr ",
 "LORA": "ell o'vv arr eeyy ",
 "RJ45": "arr jeyy to'rt besh ",
 "OVF": "o'vv vii eff ",
 "WEBID": "dabilyu iii bii ayy dee ",
 "PT": "ppii tii ",
 "GERD": "jii iii arr dee ",
 "PRP": "ppii arr ppii ",
 "BUN": "bii yuu enn ",
 "DSZV": "dee es zed vii ",
 "NCP": "enn sii ppii ",
 "SDP": "es dee ppii ",
 "SPMS": "es ppii em es ",
 "SQL": "es qyuu ell ",
 "OLT": "o'vv ell tii ",
 "SARS": "es eeyy arr es ",
 "PO2": "ppii o'vv ikki ",
 "SONET": "es o'vv enn iii tii ",
 "DLP": "dee ell ppii ",
 "CRM": "sii arr em ",
 "SWIFT": "es dabilyu ayy eff tii ",
 "FUP": "eff yuu ppii ",
 "SSH": "es es eych ",
 "DWDM": "dee dabilyu dee em ",
 "WLAN": "dabilyu ell eeyy enn ",
 "DGK": "dee jii kiyy ",
 "RIP": "arr ayy ppii ",
 "PTA": "ppii tii eeyy ",
 "ROOT CA": "arr o'vv o'vv tii sii eeyy ",
 "USB": "yuu es bii ",
 "DPT": "dee ppii tii ",
 "CDMA": "sii dee em eeyy ",
 "XML": "eks em ell ",
 "MDS": "em dee es ",
 "DNSSEC": "dee enn es es iii sii ",
 "STAAS": "es tii eeyy eeyy es ",
 "PET": "ppii iii tii ",
 "AML": "eeyy em ell ",
 "OSPF": "o'vv es ppii eff ",
 "ARP": "eeyy arr ppii ",
 "SES": "es iii es ",
 "PTSD": "ppii tii es dee ",
 "BMD": "bii em dee ",
 "AS": "eeyy es ",
 "CAAS": "sii eeyy eeyy es ",
 "DAN": "dee eeyy enn ",
 "PDF": "ppii dee eff ",
 "HISS": "eych ayy es es ",
 "DOC": "dee o'vv sii ",
 "BUP": "bii yuu ppii ",
 "DRAAS": "dee arr eeyy eeyy es ",
 "NFV": "enn eff vii ",
 "XP": "eks ppii ",
 "DIFFSERV": "dee ayy eff eff es iii arr vii ",
 "HMAC": "eych em eeyy sii ",
 "PGP": "ppii jii ppii ",
 "UFC": "yuu eff sii ",
 "SNAP": "es enn eeyy ppii ",
 "PMS": "ppii em es ",
 "EDR": "iii dee arr ",
 "WI-FI": "dabilyu ayy   eff ayy ",
 "TTS": "tii tii es ",
 "ADHD": "eeyy dee eych dee ",
 "ICU": "ayy sii yuu ",
 "NVRAM": "enn vii arr eeyy em ",
 "RPOC": "arr ppii o'vv sii ",
 "CXR": "sii eks arr ",
 "JBOD": "jeyy bii o'vv dee ",
 "GPU": "jii ppii yuu ",
 "BMP": "bii em ppii ",
 "SCC": "es sii sii ",
 "VDI": "vii dee ayy ",
 "PRIVATE KEY": "ppii arr ayy vii eeyy tii iii kiyy iii vay ",
 "FBC": "eff bii sii ",
 "DM": "dee em ",
 "FIDE": "eff ayy dee iii ",
 "HSRP": "eych es arr ppii ",
 "KB": "kiyy bii ",
 "XSS": "eks es es ",
 "UEM": "yuu iii em ",
 "MPV": "em ppii vii ",
 "YUM": "vay yuu em ",
 "HUS": "eych yuu es ",
 "YAIM": "vay eeyy ayy em ",
 "IETF": "ayy iii tii eff ",
 "HCT": "eych sii tii ",
 "3DES": "uch dee iii es ",
 "PPMS": "ppii ppii em es ",
 "STP": "es tii ppii ",
 "HBA": "eych bii eeyy ",
 "GSM": "jii es em ",
 "MTRK": "em tii arr kiyy ",
 "OA": "o'vv eeyy ",
 "CRUD": "sii arr yuu dee ",
 "AVI": "eeyy vii ayy ",
 "CAD": "sii eeyy dee ",
 "PKEI": "ppii kiyy iii ayy ",
 "CD8": "sii dee sakkiz ",
 "XLS": "eks ell es ",
 "MRI": "em arr ayy ",
 "IHF": "ayy eych eff ",
 "GPG": "jii ppii jii ",
 "YAML": "vay eeyy em ell ",
 "KMK": "kiyy em kiyy ",
 "PGW": "ppii jii dabilyu ",
 "TTJ": "tii tii jeyy ",
 "MMTV": "em em tii vii ",
 "HIFZ": "eych ayy eff zed ",
 "G6PD": "jii olti ppii dee ",
 "ISO": "ayy es o'vv ",
 "JSP": "jeyy es ppii ",
 "BOOTP": "bii o'vv o'vv tii ppii ",
 "SMB": "es em bii ",
 "UZI": "yuu zed ayy ",
 "CARP": "sii eeyy arr ppii ",
 "BMK": "bii em kiyy ",
 "WBO": "dabilyu bii o'vv ",
 "VQ": "vii qyuu ",
 "MRK": "em arr kiyy ",
 "RPR": "arr ppii arr ",
 "BASH": "bii eeyy es eych ",
 "BCG": "bii sii jii ",
 "IVF": "ayy vii eff ",
 "NGT": "enn jii tii ",
 "BMI": "bii em ayy ",
 "LCD": "ell sii dee ",
 "SD-WAN": "es dee   dabilyu eeyy enn ",
 "ARDS": "eeyy arr dee es ",
 "IDS": "ayy dee es ",
 "EEG": "iii iii jii ",
 "CTA": "sii tii eeyy ",
 "BTV": "bii tii vii ",
 "STIR": "es tii ayy arr ",
 "BMT": "bii em tii ",
 "VDSL": "vii dee es ell ",
 "COPD": "sii o'vv ppii dee ",
 "OTP": "o'vv tii ppii ",
 "HCV": "eych sii vii ",
 "CDP": "sii dee ppii ",
 "DSL": "dee es ell ",
 "LACP": "ell eeyy sii ppii ",
 "BAAS": "bii eeyy eeyy es ",
 "ENT": "iii enn tii ",
 "OOP": "o'vv o'vv ppii ",
 "WWN": "dabilyu dabilyu enn ",
 "KMP": "kiyy em ppii ",
 "BAT": "bii eeyy tii ",
 "TCP": "tii sii ppii ",
 "CSMA/CA": "sii es em eeyy   sii eeyy ",
 "HTTPS": "eych tii tii ppii es ",
 "SSB": "es es bii ",
 "OIV": "o'vv ayy vii ",
 "ICS": "ayy sii es ",
 "GMK": "jii em kiyy ",
 "HTTP2": "eych tii tii ppii ikki ",
 "XSLT": "eks es ell tii ",
 "NAMTV": "enn eeyy em tii vii ",
 "TTY": "tii tii vay ",
 "RSHTIOM": "arr es eych tii ayy o'vv em ",
 "TTB": "tii tii bii ",
 "AFP": "eeyy eff ppii ",
 "OCD": "o'vv sii dee ",
 "FIDO": "eff ayy dee o'vv ",
 "VTP": "vii tii ppii ",
 "CREA": "sii arr iii eeyy ",
 "HDL": "eych dee ell ",
 "DSQ": "dee es qyuu ",
 "NIC": "enn ayy sii ",
 "EC2": "iii sii ikki ",
 "VGA": "vii jii eeyy ",
 "AGC": "eeyy jii sii ",
 "TTM": "tii tii em ",
 "DOTS": "dee o'vv tii es ",
 "GAD": "jii eeyy dee ",
 "CASB": "sii eeyy es bii ",
 "BYOD": "bii vay o'vv dee ",
 "ATV": "eeyy tii vii ",
 "T4": "tii to'rt ",
 "IUD": "ayy yuu dee ",
 "WTA": "dabilyu tii eeyy ",
 "MPLS": "em ppii ell es ",
 "PAT": "ppii eeyy tii ",
 "UEBA": "yuu iii bii eeyy ",
 "HCG": "eych sii jii ",
 "TMI": "tii em ayy ",
 "LCP": "ell sii ppii ",
 "TLC": "tii ell sii ",
 "ALT": "eeyy ell tii ",
 "JWT": "jeyy dabilyu tii ",
 "RPA": "arr ppii eeyy ",
 "CSF": "sii es eff ",
 "AIBA": "eeyy ayy bii eeyy ",
 "MP4": "em ppii to'rt ",
 "ERCP": "iii arr sii ppii ",
 "URTI": "yuu arr tii ayy ",
 "RSV": "arr es vii ",
 "ISU": "ayy es yuu ",
 "HLA": "eych ell eeyy ",
 "HIRS": "eych ayy arr es ",
 "BPH": "bii ppii eych ",
 "IPSEC": "ayy ppii es iii sii ",
 "IAM": "ayy eeyy em ",
 "TPU": "tii ppii yuu ",
 "P2P": "ppii ikki ppii ",
 "PRN": "ppii arr enn ",
 "EVPN": "iii vii ppii enn ",
 "MCS": "em sii es ",
 "VRRP": "vii arr arr ppii ",
 "MMB": "em em bii ",
 "AI": "eeyy ayy ",
 "CSV": "sii es vii ",
 "PCOS": "ppii sii o'vv es ",
 "NAS": "enn eeyy es ",
 "OSS": "o'vv es es ",
 "SSD": "es es dee ",
 "TIA": "tii ayy eeyy ",
 "COPE": "sii o'vv ppii iii ",
 "SSKS": "es es kiyy es ",
 "FEV1": "eff iii vii bir ",
 "IM": "ayy em ",
 "KT": "kiyy tii ",
 "URL": "yuu arr ell ",
 "UTI": "yuu tii ayy ",
 "RSA": "arr es eeyy ",
 "LC": "ell sii ",
 "PSA": "ppii es eeyy ",
 "SLE": "es ell iii ",
 "5G": "besh jii ",
 "IPF": "ayy ppii eff ",
 "DRAM": "dee arr eeyy em ",
 "XIF": "eks ayy eff ",
 "UTM": "yuu tii em ",
 "EIG": "iii ayy jii ",
 "TFTP": "tii eff tii ppii ",
 "LAMBDA": "ell eeyy em bii dee eeyy ",
 "IV": "ayy vii ",
 "CML": "sii em ell ",
 "FISH": "eff ayy es eych ",
 "LRTI": "ell arr tii ayy ",
 "PBXR": "ppii bii eks arr ",
 "WDM": "dabilyu dee em ",
 "ISDN": "ayy es dee enn ",
 "FTV": "eff tii vii ",
 "NTU": "enn tii yuu ",
 "JSON": "jeyy es o'vv enn ",
 "X-RAY": "eks   arr eeyy vay ",
 "A1C": "eeyy bir sii ",
 "BLOWFISH": "bii ell o'vv dabilyu eff ayy es eych ",
 "EIIB": "iii ayy ayy bii ",
 "DKTM": "dee kiyy tii em ",
 "TMPM": "tii em ppii em ",
 "GRE": "jii arr iii ",
 "RFID": "arr eff ayy dee ",
 "OAK": "o'vv eeyy kiyy ",
 "PIIMA": "ppii ayy ayy em eeyy ",
 "SDN": "es dee enn ",
 "STT": "es tii tii ",
 "SCP": "es sii ppii ",
 "KEY EXCHANGE": "kiyy iii vay iii eks sii eych eeyy enn jii iii ",
 "HRT": "eych arr tii ",
 "RA": "arr eeyy ",
 "WAN": "dabilyu eeyy enn ",
 "DVQK": "dee vii qyuu kiyy ",
 "TCA": "tii sii eeyy ",
 "SVK": "es vii kiyy ",
 "APGAR": "eeyy ppii jii eeyy arr ",
 "VMX": "vii em eks ",
 "UASH": "yuu eeyy es eych ",
 "DBAAS": "dee bii eeyy eeyy es ",
 "VR": "vii arr ",
 "ASP": "eeyy es ppii ",
 "PEM": "ppii iii em ",
 "IPV6": "ayy ppii vii olti ",
 "LLM": "ell ell em ",
 "DEVOPS": "dee iii vii o'vv ppii es ",
 "GCS": "jii sii es ",
 "apple":"eppill",
 "iphone":"ayfo'n",}
 
_combined = "(" + ")\\b|\\b(".join(pattern) + ")"
